language: python
python:
  - "2.7"
  - "3.6"

env:
  - PLATFORMIO_PROJECT_DIR=examples/mbed-blink
  - PLATFORMIO_PROJECT_DIR=examples/mbed-dsp
  - PLATFORMIO_PROJECT_DIR=examples/mbed-events
  - PLATFORMIO_PROJECT_DIR=examples/mbed-rtos
  - PLATFORMIO_PROJECT_DIR=examples/mbed-serial
  - PLATFORMIO_PROJECT_DIR=examples/mbed-custom-target
  - PLATFORMIO_PROJECT_DIR=examples/zephyr-blink
  # - PLATFORMIO_PROJECT_DIR=examples/zephyr-drivers-watchdog
  - PLATFORMIO_PROJECT_DIR=examples/zephyr-synchronization

# Zephyr framework doesn't support python 2
jobs:
  exclude:
    - python: "2.7"
      env: PLATFORMIO_PROJECT_DIR=examples/zephyr-blink
    - python: "2.7"
      env: PLATFORMIO_PROJECT_DIR=examples/zephyr-drivers-watchdog
    - python: "2.7"
      env: PLATFORMIO_PROJECT_DIR=examples/zephyr-synchronization
  
install:
  - pip install -U https://github.com/platformio/platformio/archive/develop.zip
  - platformio platform install file://.

script:
  - platformio run -d $PLATFORMIO_PROJECT_DIR

notifications:
  email: false

  slack:
    rooms:
      secure: VwbEloRRhOM7q07DhjeoTqM+6vYwaRae1RwlyYOmWWTDXA7epK5Q9vGLm3WYrp/uefp10APCz/lzoXdrj4WGY6xfMdi387uJopoIqBJKiOwGFXVHjqwV6lQ6yenWgvQa+EiWeZ2lkk6pWg9kcsnGL++b4jEA29l042DkpV/5FKlcU+N0xbkvyjIA7djLGFc0SYHbj44oUC2O2x6E/iO3Of+Ldyj47BU8B/Fk6yWH5jXhXxDpHOGljLtEkP1FHQg0Tmb04wHzkhIKRqxjJ/M16KFdc2+VySG17byWEv07jW8tSHMIe7mkJunLsleNgC0H1zuu0F1AouHcoh4d0855RFpAbzWMqesytmnbLq/Q1QS5fOJAB2ooeVtUFK52Ka5kehZJOXiJeSklU1G8YNju2qU+rHrxc3wLQ9n29v1h2vE4lDqFAIX+Ow7b/EhXlNlEi3pdE+GT0Z1ar/LhfzS4WYw4NOQ9OeJE8uTUdJF9d9O/0pX8mBKZRwC8IfRq68eHRwcdvKyqqMSkc/k5H1C+GKaN0iBbDXN9irzFyjpF97KsbVAYXx/oZI5yBAndaHBFKQumyuZ9Wreh1pcDfuPjDtTnacBXMmVLza5DCTskf0zJobVXxD3DmrGk81qz7HuBsGzV9Hl+MLe+vxBKTSlMzZcAKVq3Gl1jTeYfqyIecSk=
    on_failure: always
    on_success: change
